"""The cover letter is written, not printed.

The letter this replaces put experience facts into the body verbatim, so a paragraph in the
middle of it read:

    Full-Stack Developer — Carepool

-- a database row with the full stop missing, between two sentences. Underneath it sat
"Generated by LocalApply from 12 verified profile facts", on a document going to an
employer. Those are the two failures this module exists to keep out.

The rules here are the ones a person notices: every paragraph is a sentence, the tense
matches the dates, "a AI Engineer" never appears, and nothing internal to the tool is
printed on the page.
"""

from __future__ import annotations

import re
from uuid import uuid4

import pytest
from localapply.documents import prose
from localapply.documents.generator import DocumentGenerator
from localapply.documents.matching import rank_experience
from localapply.documents.render import render_html
from localapply.profile.facts import FactCategory, FactStatus

JOB = """We are hiring an AI Engineer to build retrieval-augmented systems.

Requirements:
- Strong Python
- FastAPI
- Experience with RAG
- Docker
- Kubernetes
"""


class Fact:
    def __init__(self, key, value, category, detail=None):
        self.id = uuid4()
        self.key, self.value, self.category = key, value, category
        self.detail = detail or {}
        self.status = FactStatus.ACCEPTED.value


@pytest.fixture
def facts():
    return [
        Fact("full_name", "Haydar Farhat", FactCategory.IDENTITY.value),
        Fact("current_title", "AI Engineer", FactCategory.IDENTITY.value),
        Fact("email", "h@example.com", FactCategory.IDENTITY.value),
        Fact("phone", "+961 76 943 608", FactCategory.IDENTITY.value),
        Fact("city", "Beirut", FactCategory.IDENTITY.value),
        Fact("country", "Lebanon", FactCategory.IDENTITY.value),
        Fact("Python", "Python", FactCategory.SKILL.value),
        Fact("FastAPI", "FastAPI", FactCategory.SKILL.value),
        Fact("Docker", "Docker", FactCategory.SKILL.value),
        Fact("RAG", "RAG", FactCategory.SKILL.value),
        Fact(
            "Full-Stack Developer — Carepool", "Full-Stack Developer — Carepool",
            FactCategory.EXPERIENCE.value,
            {"role": "Full-Stack Developer", "organisation": "Carepool",
             "dates": "2023 - Present",
             "bullets": ["Engineered backend services and REST APIs using Laravel.",
                         "Built a retrieval pipeline over 40k support documents."]},
        ),
        Fact(
            "AI Engineer — Fitly", "AI Engineer — Fitly",
            FactCategory.EXPERIENCE.value,
            {"role": "AI Engineer", "organisation": "Fitly", "dates": "2021 - 2023",
             "bullets": ["Shipped a RAG assistant on FastAPI serving 2k daily queries."]},
        ),
    ]


@pytest.fixture
def plan(facts):
    return DocumentGenerator().cover_letter(
        facts, job_title="AI Engineer", company="Northwind Analytics", description=JOB
    )


@pytest.fixture
def paragraphs(plan):
    body = next(s for s in plan.sections if s.heading == "Letter")
    return [item.text for item in body.items]


@pytest.fixture
def html(plan):
    return render_html(plan)


# --------------------------------------------------------------------------------------
# Every paragraph is prose
# --------------------------------------------------------------------------------------


def test_no_paragraph_is_a_bare_headline_row(paragraphs):
    """The regression. A row has no verb and no full stop; a sentence has both."""
    for text in paragraphs:
        assert text.rstrip()[-1] in ".!?", f"not a sentence: {text!r}"
        assert len(text.split()) >= 6, f"reads as a row, not a paragraph: {text!r}"
        assert " I " in f" {text} ", f"no subject anywhere in: {text!r}"


def test_experience_is_written_as_a_sentence(paragraphs):
    body = " ".join(paragraphs)
    assert "At Carepool (2023 - Present) I work as a Full-Stack Developer" in body
    # The verb-initial bullets fold into the sentence rather than sitting beside it.
    assert "where I have engineered backend services" in body


def test_the_flat_headline_never_appears_on_its_own(paragraphs):
    assert "Full-Stack Developer — Carepool" not in paragraphs
    assert "AI Engineer — Fitly" not in paragraphs


def test_a_current_role_is_written_in_the_present_tense(paragraphs):
    body = " ".join(paragraphs)
    assert "Carepool (2023 - Present) I work as" in body
    assert "Carepool (2023 - Present) I worked as" not in body


def test_a_finished_role_is_written_in_the_past_tense(paragraphs):
    assert any("At Fitly (2021 - 2023) I worked as" in p for p in paragraphs)


def test_the_current_role_is_written_first(paragraphs):
    """Relevance chooses which roles appear; chronology decides their order. Leading with
    a job that ended and following it with the one still held reads as an error."""
    body = " ".join(paragraphs)
    assert body.index("Carepool") < body.index("Fitly")


def test_articles_agree_with_the_following_word(paragraphs):
    body = " ".join(paragraphs)
    assert "a AI Engineer" not in body
    assert "an AI Engineer" in body
    assert "a Full-Stack Developer" in body


def test_the_skill_list_is_not_repeated_in_full(paragraphs):
    """The opening names the strongest two; the rest are held for the fit paragraph. The
    old letter listed the same four technologies twice in five sentences."""
    opening = paragraphs[0]
    fit = next(p for p in paragraphs if p.startswith("The posting also asks"))
    named_twice = [s for s in ("Python", "FastAPI", "Docker", "RAG")
                   if s in opening and s in fit]
    assert named_twice == [], f"named in both the opening and the fit paragraph: {named_twice}"


def test_a_missing_requirement_is_named_rather_than_hidden(paragraphs):
    """Kubernetes is required by the posting and absent from the profile."""
    body = " ".join(paragraphs)
    assert "Kubernetes" in body
    assert "not worked with Kubernetes" in body


def test_the_letter_closes_with_a_way_to_reply(paragraphs):
    assert "h@example.com" in paragraphs[-1]


def test_the_name_is_not_repeated_in_the_body(paragraphs):
    """It is already the letterhead and the signature."""
    assert all("Haydar Farhat" not in p for p in paragraphs)


# --------------------------------------------------------------------------------------
# Nothing internal reaches the page
# --------------------------------------------------------------------------------------


def test_no_generated_by_footer(html):
    """This text was printed over the signature, and the parser then read it back in as an
    experience bullet on the next import. It has no business on either side."""
    assert "Generated by LocalApply" not in html
    assert "<footer" not in html.lower()
    assert "verified profile facts" not in html


def test_no_css_generated_content(html):
    styles = html.split("</style>")[0]
    assert "::after" not in styles
    assert "::before" not in styles


def test_the_contact_line_is_real_text(html):
    body = html.split("</style>", 1)[1]
    assert "h@example.com" in body
    assert "Beirut, Lebanon" in body


def test_the_company_and_role_are_addressed(html):
    body = html.split("</style>", 1)[1]
    assert "Northwind Analytics" in body
    assert "Re: AI Engineer" in body


def test_every_paragraph_is_grounded(plan, facts):
    from localapply.documents.generator import assert_grounded

    assert_grounded(plan, {f.id for f in facts})


# --------------------------------------------------------------------------------------
# The composition helpers
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("phrase", "expected"),
    [
        ("AI Engineer", "an"),      # initialism read letter by letter
        ("SRE", "an"),              # "ess"
        ("ML Engineer", "an"),      # "em"
        ("Full-Stack Developer", "a"),
        ("engineer", "an"),
        ("university researcher", "a"),   # spelled with a vowel, said with a consonant
        ("", "a"),
    ],
)
def test_article_follows_sound_not_spelling(phrase, expected):
    assert prose.article(phrase) == expected


@pytest.mark.parametrize(
    "dates",
    ["2023 - Present", "Jan 2023 – present", "2023 to date", "2022 - Current", "2024 - now"],
)
def test_open_ended_dates_read_as_current(dates):
    assert prose.is_current(dates)


@pytest.mark.parametrize("dates", ["2021 - 2023", "1 Year", "Summer 2022", ""])
def test_closed_dates_do_not(dates):
    assert not prose.is_current(dates)


def test_oxford_separates_a_run_readably():
    assert prose.oxford(["Python"]) == "Python"
    assert prose.oxford(["Python", "Docker"]) == "Python and Docker"
    assert prose.oxford(["a", "b", "c"]) == "a, b and c"
    assert prose.oxford(["a", "b"], "or") == "a or b"


def test_oxford_commas_before_a_conjunction_when_the_parts_have_their_own():
    """"engineered A and B and built C" is one "and" too many to parse on first read."""
    joined = prose.oxford(["engineered A and B", "built C"])
    assert joined == "engineered A and B, and built C"


def test_a_bullet_that_is_not_verb_initial_stays_its_own_sentence():
    """Lowercasing it would produce "react Native app work", which is worse than an extra
    sentence."""
    fact = Fact("x", "x", FactCategory.EXPERIENCE.value,
                {"role": "Developer", "organisation": "Acme",
                 "bullets": ["React Native app development for two clients."]})
    text = prose.experience_paragraph(fact, fact.detail["bullets"])

    assert "react Native" not in text
    assert "React Native app development for two clients." in text
    assert "where I" not in text


def test_an_entry_with_no_structure_still_yields_a_sentence():
    """Not every parsed CV gives up a role and an employer. It must still read as prose."""
    fact = Fact("x", "Software work at several agencies", FactCategory.EXPERIENCE.value)
    text = prose.experience_paragraph(fact, [])

    assert text == "Software work at several agencies."


# --------------------------------------------------------------------------------------
# Ranking
# --------------------------------------------------------------------------------------


def test_experience_is_ranked_on_its_bullets_not_only_its_title():
    """A "Full-Stack Developer" whose bullets are entirely RAG work scored zero against a
    RAG posting while the headline was the only thing read."""
    rag_in_bullets = Fact(
        "Full-Stack Developer — Carepool", "Full-Stack Developer — Carepool",
        FactCategory.EXPERIENCE.value,
        {"role": "Full-Stack Developer", "organisation": "Carepool",
         "bullets": ["Built a RAG pipeline on FastAPI."]},
    )
    unrelated = Fact(
        "Support Engineer — Helpdesk", "Support Engineer — Helpdesk",
        FactCategory.EXPERIENCE.value,
        {"role": "Support Engineer", "organisation": "Helpdesk", "bullets": ["Answered tickets."]},
    )

    ranked = rank_experience([unrelated, rag_in_bullets], ["RAG", "FastAPI"])
    assert ranked[0] is rag_in_bullets


def test_the_letter_has_no_stray_double_spaces(paragraphs):
    """A sentence form with an empty slot leaves a visible gap."""
    for text in paragraphs:
        assert not re.search(r"\S  +\S", text), f"double space in: {text!r}"
        assert " ." not in text and " ," not in text
