"""The CV obeys published ATS parsing rules.

Written after a user reported the generated CV "doesn't look like a CV, it's just stating
facts". The formatting rules below are not taste -- they are the mechanical constraints
applicant tracking systems and their vendors publish, and the previous template broke
several at once: a two-column flex row for dates, an invented "APPLYING FOR" heading, body
content in a <footer>, and separators made of CSS generated content.

Sources for the rules: Jobscan's ATS resume format checklist, and the XYZ bullet formula
(Laszlo Bock) for content.
"""

from __future__ import annotations

import re
from uuid import uuid4

import pytest
from localapply.documents.generator import DocumentGenerator
from localapply.documents.render import build_contact_line, render_html
from localapply.documents.taxonomy import group_skills, is_presentable
from localapply.profile.facts import FactCategory, FactStatus

JOB = "Requirements:\n- Python\n- FastAPI\n- Docker\n\nNice to have:\n- Kubernetes\n"


class Fact:
    def __init__(self, key, value, category, detail=None):
        self.id = uuid4()
        self.key, self.value, self.category = key, value, category
        self.detail = detail or {}
        self.status = FactStatus.ACCEPTED.value


@pytest.fixture
def facts():
    return [
        Fact("full_name", "Haydar Farhat", FactCategory.IDENTITY.value),
        Fact("current_title", "AI Engineer", FactCategory.IDENTITY.value),
        Fact("email", "h@example.com", FactCategory.IDENTITY.value),
        Fact("phone", "+961 76 943 608", FactCategory.IDENTITY.value),
        Fact("city", "Beirut", FactCategory.IDENTITY.value),
        Fact("country", "Lebanon", FactCategory.IDENTITY.value),
        Fact("linkedin_url", "https://www.linkedin.com/in/haydar/", FactCategory.IDENTITY.value),
        Fact("Python", "Python", FactCategory.SKILL.value),
        Fact("Laravel", "Laravel", FactCategory.SKILL.value),
        Fact("Docker", "Docker", FactCategory.SKILL.value),
        Fact("OOP", "OOP", FactCategory.SKILL.value),
        Fact("phrase", "Python-based AI workflows", FactCategory.SKILL.value),
        Fact(
            "Full-Stack Developer — Carepool",
            "Full-Stack Developer — Carepool",
            FactCategory.EXPERIENCE.value,
            {
                "role": "Full-Stack Developer", "organisation": "Carepool",
                "dates": "2023 - Present",
                "bullets": ["Engineered backend services and REST APIs using Laravel."],
            },
        ),
    ]


@pytest.fixture
def cv(facts):
    return render_html(
        DocumentGenerator().tailored_cv(
            facts, job_title="AI Engineer", company="Northwind", description=JOB
        )
    )


def body_of(html: str) -> str:
    return html.split("</style>", 1)[1]


# --------------------------------------------------------------------------------------
# Layout: single column, no constructs parsers cannot read
# --------------------------------------------------------------------------------------


def test_no_tables_or_text_boxes(cv):
    for tag in ("<table", "<td", "<tr", "<textarea", "<img", "<svg", "<canvas"):
        assert tag not in cv.lower(), f"{tag} is not ATS-parseable"


def test_no_multi_column_layout(cv):
    """The old template used `display: flex; justify-content: space-between` to right-align
    dates -- a two-column row inside the content."""
    styles = cv.split("</style>")[0]
    for rule in ("display: flex", "display:flex", "display: grid", "display:grid",
                 "column-count", "float:", "float :"):
        assert rule not in styles, f"{rule!r} creates a multi-column layout"


def test_nothing_in_a_header_or_footer_element(cv):
    """Parsers routinely drop header/footer content, and the old footer's "Generated by
    LocalApply from N verified profile facts" was noise on a document sent to an employer --
    a variant of it even leaked into the body as a bullet."""
    assert "<footer" not in cv.lower()
    assert "<header" not in cv.lower()
    assert "Generated by LocalApply" not in cv


def test_no_css_generated_content(cv):
    """`::after { content: ... }` renders but is not document text; a contact line must
    never depend on it."""
    styles = cv.split("</style>")[0]
    assert "content:" not in styles.replace("box-sizing", "")
    assert "::after" not in styles
    assert "::before" not in styles


def test_web_safe_font_stack(cv):
    styles = cv.split("</style>")[0]
    assert re.search(r"font-family:\s*(Calibri|Arial|Georgia|Helvetica|Times)", styles), (
        "body font must be one a parser and a printer both have"
    )


def test_bullets_are_a_real_list(cv):
    assert "<ul" in cv and "<li>" in cv
    assert "list-style-type: disc" in cv.split("</style>")[0]


# --------------------------------------------------------------------------------------
# Structure: standard headings only
# --------------------------------------------------------------------------------------


STANDARD_HEADINGS = {"SUMMARY", "SKILLS", "EXPERIENCE", "PROJECTS", "EDUCATION",
                     "CERTIFICATIONS", "WORK EXPERIENCE"}


def test_only_standard_section_headings(cv):
    headings = {h.strip().upper() for h in re.findall(r"<h2>(.*?)</h2>", cv, re.DOTALL)}
    unexpected = headings - STANDARD_HEADINGS
    assert not unexpected, f"non-standard headings a parser cannot bucket: {unexpected}"


def test_the_company_applied_to_is_not_printed(cv):
    assert "Northwind" not in cv
    assert "APPLYING FOR" not in cv.upper()


# --------------------------------------------------------------------------------------
# Contact line
# --------------------------------------------------------------------------------------


def test_contact_line_is_one_plain_line():
    line = build_contact_line(
        {
            "email": "h@example.com", "phone": "+961 76 943 608",
            "city": "Beirut", "country": "Lebanon",
            "linkedin_url": "https://www.linkedin.com/in/haydar/",
        }
    )
    assert "\n" not in line
    assert "h@example.com" in line
    # City and country read as one place, not two separate items.
    assert "Beirut, Lebanon" in line
    # Links are shown the way a CV shows them.
    assert "linkedin.com/in/haydar" in line
    assert "https://" not in line
    assert "www." not in line


def test_contact_line_skips_missing_values():
    assert build_contact_line({"email": "a@b.c"}) == "a@b.c"
    assert build_contact_line({}) == ""


# --------------------------------------------------------------------------------------
# Skills: grouped, and free of things that are not skills
# --------------------------------------------------------------------------------------


def test_skills_are_grouped_not_a_wall(cv):
    body = body_of(cv)
    assert "Languages:" in body, "skills should be grouped for a reader who skims"
    assert "Python" in body


def test_cs_topics_and_phrases_are_not_listed_as_skills(cv):
    body = body_of(cv)
    assert "OOP" not in body
    assert "Python-based AI workflows" not in body


def test_taxonomy_keeps_real_technologies():
    for skill in ("Python", "Laravel", "React Native", "MySQL", "Docker", "RAG"):
        assert is_presentable(skill), f"{skill} is a real skill and must survive"


def test_taxonomy_groups_in_conventional_order():
    groups = [name for name, _ in group_skills(["Docker", "Python", "MySQL", "Laravel"])]
    assert groups.index("Languages") < groups.index("Frameworks") < groups.index(
        "Tools & Platforms"
    )


# --------------------------------------------------------------------------------------
# Experience entries
# --------------------------------------------------------------------------------------


def test_role_employer_and_dates_are_on_one_text_line(cv):
    """Inline rather than right-aligned in a second column, so the reading order a parser
    sees matches the reading order a person sees."""
    head = re.search(r'<p class="entry-head">(.*?)</p>', cv, re.DOTALL)
    assert head is not None
    text = re.sub(r"<[^>]+>", "", head.group(1))
    assert "Full-Stack Developer" in text
    assert "Carepool" in text
    assert "2023 - Present" in text


def test_bullets_are_separate_from_the_headline(cv):
    head = re.search(r'<p class="entry-head">(.*?)</p>', cv, re.DOTALL).group(1)
    assert "Engineered backend services" not in head, (
        "a bullet must not be merged into the role line"
    )
    assert "<li>Engineered backend services" in cv.replace("\n", "").replace("  ", "")
