"""generated documents

Revision ID: 4e228bdde5e2
Revises: 7fe8f220df0f
Create Date: 2026-08-24 15:38:37.634861
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '4e228bdde5e2'
down_revision: str | None = '7fe8f220df0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fact_ids', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_breakdown', sa.JSON(), nullable=True),
    sa.Column('generator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_job_id'), 'generated_documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_kind'), 'generated_documents', ['kind'], unique=False)
    op.create_index(op.f('ix_generated_documents_profile_id'), 'generated_documents', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_documents_profile_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_kind'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_job_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    # ### end Alembic commands ###
