"""track generated pdf hash

Revision ID: 9f9138c9890e
Revises: d45f89cc6510
Create Date: 2026-08-24 18:28:05.335937
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '9f9138c9890e'
down_revision: str | None = 'd45f89cc6510'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_documents', sa.Column('pdf_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_generated_documents_pdf_sha256'), 'generated_documents', ['pdf_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_documents_pdf_sha256'), table_name='generated_documents')
    op.drop_column('generated_documents', 'pdf_sha256')
    # ### end Alembic commands ###
