"""Saved searches, and one row per posting per board.

Phase 6 brings jobs in from board APIs instead of by hand, which makes duplication possible
for the first time: running the same search twice would otherwise create a second copy of
every job on it -- and the copy has its own application, its own state, and no memory that
you already cancelled the first.

Hand-written rather than autogenerated. Autogenerate against this schema has previously
proposed dropping a column it did not recognise, and a unique constraint added over data
that already violates it fails at the worst possible moment. So the duplicates are cleaned
up first, in the same migration, and only then is the constraint added.

Revision ID: b3d7c1a94e20
Revises: 9f9138c9890e
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "b3d7c1a94e20"
down_revision: str | None = "9f9138c9890e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("handle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("include", sa.JSON(), nullable=True),
        sa.Column("exclude", sa.JSON(), nullable=True),
        sa.Column("min_score", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_searches_profile_id"), "saved_searches", ["profile_id"], unique=False
    )
    op.create_index(op.f("ix_saved_searches_source"), "saved_searches", ["source"], unique=False)

    # Every existing row was created by hand or by a run, so external_id is NULL on all of
    # them and none can collide. Cleaning up first is cheap insurance rather than a
    # response to known data: a constraint that fails on upgrade leaves the schema half
    # applied, and the person it fails for has no way to know which rows to delete.
    #
    # The newest duplicate wins: it is the one whose application has been worked on.
    op.execute(
        """
        DELETE FROM jobs
        WHERE external_id IS NOT NULL
          AND id NOT IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY source, external_id ORDER BY discovered_at DESC
                       ) AS rn
                FROM jobs
                WHERE external_id IS NOT NULL
            ) ranked
            WHERE rn = 1
          )
          AND id NOT IN (SELECT job_id FROM applications)
        """
    )

    # NULLs do not collide under a unique constraint on any supported backend, so every job
    # added by hand -- which is all of them before this phase -- is unaffected.
    op.create_unique_constraint(
        "uq_jobs_source_external_id", "jobs", ["source", "external_id"]
    )

    # The per-application history query on GET /jobs/{id} was a table scan. Cheap to fix
    # here while the table is small, and it only grows.
    op.create_index(op.f("ix_audit_logs_target"), "audit_logs", ["target"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_audit_logs_target"), table_name="audit_logs")
    op.drop_constraint("uq_jobs_source_external_id", "jobs", type_="unique")
    op.drop_index(op.f("ix_saved_searches_source"), table_name="saved_searches")
    op.drop_index(op.f("ix_saved_searches_profile_id"), table_name="saved_searches")
    op.drop_table("saved_searches")
