"""structured fact detail

Revision ID: d45f89cc6510
Revises: 4e228bdde5e2
Create Date: 2026-08-24 17:23:15.513766
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'd45f89cc6510'
down_revision: str | None = '4e228bdde5e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_facts', sa.Column('detail', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_facts', 'detail')
    # ### end Alembic commands ###
